GET /p/titleattr HTTP/1.1
Accept-Encoding: gzip
accept-diff: true

--- response ---
HTTP 200
Cache-Control: no-cache
Cache-Offline: true
Etag: e69a5a005441836fb419c6cce29007f5310c7f04
template-tag: c2c61b5c6b733e5bcbf902f14acf9ebe96386431
template-change: true
Content-Type: text/html;charset=utf-8
Content-Length: 131
Date: Fri, 09 Oct 2026 10:31:36 GMT

[body decoded from content-encoding=identity]
<!DOCTYPE html><html><head><title lang="en">Shop</title></head><body><!--sonicdiff-p--><p>1</p><!--sonicdiff-p-end--></body></html>