GET /p/titles HTTP/1.1
Accept-Encoding: gzip
accept-diff: true

--- response ---
HTTP 200
Cache-Control: no-cache
Cache-Offline: true
Etag: 429e1afc55f9b2241b0b03450b8779c88c85ff85
template-tag: adb5e40dd0a955603f0eb184d6555bdf4c99f068
template-change: true
Content-Type: text/html;charset=utf-8
Content-Length: 152
Date: Fri, 09 Oct 2026 10:31:36 GMT

[body decoded from content-encoding=identity]
<!DOCTYPE html><html><head><TITLE>Upper</TITLE></head><body><svg><title>Icon</title></svg><!--sonicdiff-p--><p>1</p><!--sonicdiff-p-end--></body></html>