GET /p/mismatch HTTP/1.1
Accept-Encoding: gzip
accept-diff: true

--- response ---
HTTP 200
Cache-Control: no-cache
Cache-Offline: true
Etag: aafeac2963624985f8873b7868ad934ca069f460
template-tag: 0ba8b8bbfb74d870558693053fc2976d1ce571dc
template-change: true
Content-Type: text/html;charset=utf-8
Content-Length: 207
Date: Fri, 09 Oct 2026 10:31:36 GMT

[body decoded from content-encoding=identity]
<!DOCTYPE html><html><head><meta charset="utf-8"><title>Shop</title></head><body><header>Static header</header><!--sonicdiff-aaa--><p>m</p><!--sonicdiff-bbb-end--><footer>Static footer</footer></body></html>