GET /p/nomark HTTP/1.1
Accept-Encoding: gzip
accept-diff: true
If-None-Match: 0000000000000000000000000000000000000000
template-tag: da98efe1f784a71546ad3f20cf8a7d2dbb03f07e

--- response ---
HTTP 200
Host: 127.0.0.1:18082
Date: Fri, 09 Oct 2026 10:31:36 GMT
Connection: close
X-Powered-By: PHP/8.3.35
Cache-Control: no-cache
Cache-Offline: true
Etag: df1595f719efdf5660cbd2fcdbadfd70b0d77c36
template-tag: da98efe1f784a71546ad3f20cf8a7d2dbb03f07e
template-change: false
Content-Length: 166
Content-type: text/html; charset=UTF-8

[body decoded from content-encoding=identity]
{"data":{"{title}":"<title>Shop<\/title>"},"template-tag":"da98efe1f784a71546ad3f20cf8a7d2dbb03f07e","html-sha1":"df1595f719efdf5660cbd2fcdbadfd70b0d77c36","diff":""}