GET /p/nested HTTP/1.1
Accept-Encoding: gzip
accept-diff: true

--- response ---
HTTP 200
Content-Type: text/html; charset=utf-8
Content-Encoding: gzip
Etag: 29f85b405ef34d1be234b87023e35b34554b621c
template-tag: 091908fd77ee9eead277a667f48310990632d285
Cache-Offline: true
template-change: true
Date: Fri, 09 Oct 2026 10:31:36 GMT
Connection: keep-alive
Keep-Alive: timeout=5
Transfer-Encoding: chunked

[body decoded from content-encoding=gzip]
<!DOCTYPE html><html><head><meta charset="utf-8"><title>Shop</title></head><body><header>Static header</header><!--sonicdiff-outer--><div><!--sonicdiff-inner--><p>in</p><!--sonicdiff-inner-end--></div><!--sonicdiff-outer-end--><footer>Static footer</footer></body></html>