GET /p/nested HTTP/1.1
Accept-Encoding: gzip
accept-diff: true
If-None-Match: 0000000000000000000000000000000000000000
template-tag: 091908fd77ee9eead277a667f48310990632d285

--- response ---
HTTP 200
Content-Type: text/html; charset=utf-8
Content-Encoding: gzip
Etag: 29f85b405ef34d1be234b87023e35b34554b621c
template-tag: 091908fd77ee9eead277a667f48310990632d285
Cache-Offline: true
template-change: false
Date: Fri, 09 Oct 2026 10:31:36 GMT
Connection: keep-alive
Keep-Alive: timeout=5
Transfer-Encoding: chunked

[body decoded from content-encoding=gzip]
{"data":{"{title}":"<title>Shop</title>","{outer}":"<!--sonicdiff-outer--><div><!--sonicdiff-inner--><p>in</p><!--sonicdiff-inner-end-->"},"diff":"","html-sha1":"29f85b405ef34d1be234b87023e35b34554b621c","template-tag":"091908fd77ee9eead277a667f48310990632d285"}